import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen font-['Virgil'] bg-[#121212]">
        <div className="container h-screen border-4 rounded-3xl flex flex-col items-center justify-center gap-12 px-4 ">
          <div className="mb-2 justify-between container flex flex-row  ">
            <div className="ml-6">
              <Image src={"globe.svg"} height={48} width={48} alt="Globe for language selection" />
            </div>
            <div className="border-4 px-4 py-2 rounded-2xl text-2xl mr-6">
              1/24
            </div>
          </div>
          <div className="text-5xl border-4 px-6 py-4 rounded-3xl">
            Frigorifero
          </div>
          <div className="my-10"></div>
          <div className="text-3xl border-4 px-6 py-4 rounded-3xl">
            Show Solution
          </div>
          <div className="mb-36"></div>
          <div className="text-4xl border-b-4 px-1 py-1 rounded-md">
            <Link href={'/progress'}>
              Progress
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
