import { useSession } from "next-auth/react";
import Head from "next/head";
import type { NextPage } from "next/types";
import { api } from "../utils/api";

const Home: NextPage = () => {
    const { data: session } = useSession();
    if (!session?.user) {
        return null
    }


    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProgressPage userId={session.user.id} />
        </>
    );
};

export default Home;

function ProgressPage({ userId }: { userId: string }) {
    const { data: user } = api.user.getById.useQuery({
        id: userId,
    })
    console.log(user)
    return <main className="min-h-screen flex flex-col items-center font-['Virgil'] bg-[#121212] justify-between">
    </main>
}